version: '3'

services:
  flask_app:
    container_name: flask_app
    build: ./flask_app
    ports:
      - "8080:8080"
    command: gunicorn -b 0.0.0.0:8000 wsgi:app
  
  nginx:
    container_name: nginx
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - flask_app
